name: CI-CD
on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Passo 01
        run: echo "Construir imagem app"
      - name: Passo 02
        run: echo "Publicar imagem DockerHub"

  CD:
    runs-on: ubuntu-latest
    steps:
      - name: Passo 01
        run: echo "Deploy app"
  
